name: Deploy CloudFormation Stack

on:
  push:
    branches: [main]
    paths:
      - 'module2/cloudformation/s3-bucket.yaml'
  workflow_dispatch: {}

permissions:
  id-token: write   # required for OIDC
  contents: read    # required for checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: arn:aws:iam::255945442255:role/ce13-kh-mod2-sharing-cloudformation
          aws-region: us-east-1
          audience: sts.amazonaws.com

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file module2/cloudformation/s3-bucket.yaml \
            --stack-name ce13-kh-mod2-sharing-s3-stack \
            --parameter-overrides BucketName=ce13khmod2sharingcloudformations3 \
            --no-fail-on-empty-changeset
